// Code generated by "core version"; DO NOT EDIT.

package freetype

const (
	// Version is the version of this package being used
	Version = "v1.0.4"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "c78ed5a"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2024-01-28 18:13"
)
