// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package freetype

const (
	Version     = "v1.0.2"
	GitCommit   = "08ab4e6"          // the commit JUST BEFORE the release
	VersionDate = "2024-01-18 18:34" // UTC
)
